### ISSUE TITLE
Baseline = 0 and tVOC = 0

### ISSUE THREAD

**Issue by CasAlexei** [Sensirion/arduino-ess#15] opened 2019-02-19 13:50 UTC
Hellow. Sensor SGPC3 works 15 hours but tVOC always equal 0 and when i read the baseline they to equal 0. Can you help me?

**Comment by winkj** [comment] 2019-02-19 15:05
Thanks for the report, I'll test with an ESS-C3 board soon (they are fairly new, so I only recently got some to test myself). some follow-up questions:

- What is your hardware setup? I assume this is using the ESS-C3 board? What arduino shield are you using?
- Is the SHTC1 working as expected when tVOC is zero?
- you said it "works 15 hours"... are there any issues after the 15 hour mark, or was that just the duration of the experiment?

**Comment by CasAlexei** [comment] 2019-02-19 15:38
I do not use the board. I connect sensor directly to the arduino-nano I2c port. I do not use SHTC1 or any other sensor. I initialize the sensor and wait >= 12 hour to read baseline. I send:
1. command - Get_feature_set_version (0x202F)
2. command - Init_air_quality (0x20AE)
3. wayt 20 sec
4. read with command - Measure_signal_and_air_quality (0x2046) every 2 sec.
And after 15 hour i read the baseline  with command - Get_Baseline (0x2015).
All 15 hour tVOC = 0 and after 15 hour baseline = 0.
If i write my value to baseline with command Set_Baseline 0x8cffh (0x201E) they stores in the sensor. But after 2-5 minutes when i read baseline = 0.
I send command - Measure_signal_and_air_quality (0x2046)
I recive rezult from sensor = 79h, 7Ch, CRC = FCh, 0h, 0h, CRC = 81h

**Comment by CasAlexei** [comment] 2019-02-19 15:42
after 15 hours it works further. I don't turn it off

**Comment by winkj** [comment] 2019-02-19 18:55
Can you reproduce the problem with the arduino-ess library? I just tried on an ESS-C3 board, and am getting non-zero readings for tVOC

**Comment by winkj** [comment] 2019-02-19 22:04
I discussed with the engineers, and the issue sounds like a brownout reset, which could occur if your power supply can't provide the peak current required during measurement.

I'll keep this open for now, please use the arduino-ess library for testing from here on out (you can simply comment out the ```return``` on [Line 65 sensirion.cpp](https://github.com/Sensirion/arduino-ess/blob/master/sensirion_ess.cpp#L65) so make ```initSensors()``` continue even if no SHT is found).

If you'd like to get support for your custom hardware and software, this would not be related to the Arduino ESS project here. In that case, it's best to use [Sensirion's Support Center](https://www.sensirion.com/en/about-us/support-center/).

**Comment by CasAlexei** [comment] 2019-02-20 07:10
![ess rezult](https://user-images.githubusercontent.com/20612675/53072893-1ecb9f80-34ef-11e9-8a7f-471fcc0e873d.png)
![my rezult](https://user-images.githubusercontent.com/20612675/53072909-2723da80-34ef-11e9-8fa5-72ca48f435c7.png)

**Comment by CasAlexei** [comment] 2019-02-20 07:19
After what time after switching on appears correct tvoc and baseline?

**Comment by winkj** [comment] 2019-02-20 17:32
It appears you're never checking the return values of ```initSensors()``` and ```measureIAQ()``` (line 15/19). It also looks like the sensor is detected as an SGP30, based on the block on line 26. Also, product type and feature set seems to be hardcoded (line 12), and it's inconsistent with the "productType = 0" printout (your printout says SGPC3, but productType = 0 indicates an SGP30).

Can you repeat that test with the sample included in the library? https://github.com/Sensirion/arduino-ess/blob/master/examples/ess/ess.ino? This one does the necessary error checking.

As for power, just to be sure: you are running it at 1.8V, with line shifters for SDA/SCL?

In my tests, I'm getting non-zero tVOC values after ~100 samples.

**Comment by CasAlexei** [comment] 2019-02-21 10:08
This is the test with the sample included in the library (while (1) in ess.initSensors() not use):
"
Error while initializing sensors: Error communicating with SHTC1
SGP30 detected, running feature set version 0
Error while measuring IAQ: ESS not initialized
Error while measuring RHT: ESS not initialized
656677.37 0.00 ovf -1.00
Error while measuring IAQ: ESS not initialized
Error while measuring RHT: ESS not initialized
656677.37 0.00 ovf -1.00 . . ."

**Comment by CasAlexei** [comment] 2019-02-21 10:15
If the sensor is SGPC30 he must work witn arduino-ess library. But i get tVOC = 0 and baseline = 0.

**Comment by CasAlexei** [comment] 2019-02-21 10:20
I bought the sensor as SGPC3.

**Comment by winkj** [comment] 2019-02-21 16:52
Thanks for verifying with the library. This looks better, so it looks like both the product type (SGPC3) and feature set (6) is now detected correctly. So based on that, it appears that the communication is working as expected.

Since the sensor is reporting zero, the most likely issue is still the peak current required during the measurement. Where is your 1.8V voltage regulator connected to, the 5V or 3.3V line?

**Comment by CasAlexei** [comment] 2019-02-22 09:30
It works. Thanks for the help. 
   The problem was in power. I connected voltage regulator L1117-1,8 to 3,3v to arduino. But this was a bad idea. I reconect to 5 volt that go from USB
and the sensor works. 
  What value should be read from the sensor in normal conditions? I read the values ​​in the room without excess gases . They are in picture after 1 hour of work. Are they correct? Can you give me  you rezult of tVOC and baseline?
 



-- 
Alexei

**Comment by rnestler** [comment] 2019-02-22 10:10
> The problem was in power. I connected voltage regulator L1117-1,8 to 3,3v to arduino. But this was a bad idea. I reconect to 5 volt that go from USB and the sensor works.

Good to hear :slightly_smiling_face: 

> I read the values ​​in the room without excess gases . They are in picture after 1 hour of work. Are they correct?

I can't see a picture in your reply. Did you send it as an email attachment?

> What value should be read from the sensor in normal conditions? 

It highly depends on your environment of course. In our office we have a few SGPs running which show between 100 and 300 ppb TVOC during the last few days.

**Comment by CasAlexei** [comment] 2019-02-22 12:07
After 1 hour work

. . . . . . .

команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 53h, CRC = D1h; 0h, 0h, CRC = 81h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 55h, CRC = 77h; 0h, 0h, CRC = 81h; => прочитали
-------------------------------------------------------------
команда 4 - Get_Baseline (0x2015)
7Ah, A3h, FBh, => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 56h, CRC = 24h; 0h, 0h, CRC = 81h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 58h, CRC = 3Bh; 0h, 0h, CRC = 81h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 55h, CRC = 77h; 0h, 2h, CRC = E3h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 55h, CRC = 77h; 0h, 1h, CRC = B0h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 55h, CRC = 77h; 0h, 0h, CRC = 81h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 59h, CRC = Ah; 0h, 0h, CRC = 81h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 56h, CRC = 24h; 0h, 2h, CRC = E3h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 53h, CRC = D1h; 0h, 2h, CRC = E3h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 5Ah, CRC = 59h; 0h, 0h, CRC = 81h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 53h, CRC = D1h; 0h, 3h, CRC = D2h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 52h, CRC = E0h; 0h, 2h, CRC = E3h; => прочитали
команда 10 - Measure_signal_and_air_quality (0x2046)
41h, 54h, CRC = 46h; 0h, 1h, CRC = B0h; => прочитали . . . . . . . . .


-- 
Alexei

**Comment by rnestler** [comment] 2019-02-22 14:55
It looks like very low TVOC values, over a few hours the baseline algorithm may adjust and give you higher values.
You can try to expose it to some TVOCs by waggling a cup of a marker pen close to the sensor for a few seconds. You should then see a spike in the TVOC values.

**Comment by winkj** [comment] 2019-02-22 17:46
@CasAlexei glad to hear it worked. The 3.3V on the Nano comes from the USB-Serial converter, which seems to have limited output current.

I'll go ahead and close this. If you have questions on the sensor itself - rather than the library - feel free to reach out to the product support specialists via Sensirion's [Support Center](https://www.sensirion.com/en/about-us/support-center/).

**Closed by winkj** 2019-02-22 17:46 UTC
