### ISSUE TITLE
i2c_write error while measuring IAQ with MKR 1010 board

### ISSUE THREAD

**Issue by druedan** [Sensirion/arduino-ess#19] opened 2020-07-14 16:03 UTC
Until recently I was using the ESS with a regular Arduino Uno, where it was working fine, but I've moved to an Arduino MKR 1010 and I'm communicating with the ESS via the I2C expansion pins.

Using the "ess" example sketch, ess.measureIAQ() is failing with "error in i2C_write". The RHT sensors are working fine and reporting accurate values. Obviously there is an issue but I'm too much of a novice to know how to fix it. Does it have something to do with a difference between the Uno and MKR 1010?

Any help is appreciated.

**Comment by winkj** [comment] 2020-07-14 16:12
I believe I have a MKR board somewhere, but will have to dig it out.

The RHT working and SGP failing sounds like it could be an issue with power... is the ESS the only board connected, or do you have other peripherals connected to the MKR?

**Comment by winkj** [comment] 2020-07-14 16:16
Also, is this on USB power or on a lipo battery?

**Comment by druedan** [comment] 2020-07-14 16:29
USB power, and the ESS is the only peripheral connected (for the moment). I think I might have a lipo laying around someplace if that's gonna help me on power.

**Comment by winkj** [comment] 2020-07-14 16:34
If anything, I'd expect USB to be better for this case... thanks for confirming, I'll see whether I can find my MKR board later today!

**Comment by druedan** [comment] 2020-07-14 17:37
Awesome, thanks.

**Comment by druedan** [comment] 2020-07-14 17:51
Just to be sure, I tried powering the ESS independent of the MKR, and tried several different jumper wires for the power as well - no change.

**Comment by winkj** [comment] 2020-07-14 19:57
I dug out an MKR1000, and believe that I found the culprit: the LED pins are conflicting with the I2C pins, since the MKR footprint is different than the Arduino Uno one. I'll try to push a hotfix in a bit.

If you want to fix this locally for the time being, just comment out line 51 in sensirion_ess.cpp (https://github.com/Sensirion/arduino-ess/blob/master/sensirion_ess.cpp#L51)

**Comment by winkj** [comment] 2020-07-14 21:09
This is now implemented in https://github.com/Sensirion/arduino-ess/tree/led_rewrite

**Comment by winkj** [comment] 2020-07-15 15:32
And released in v0.5.4; you can download it from https://github.com/Sensirion/arduino-ess/tree/v0.5.4. The update will also be available through the Arduino IDE Library manager too, whenever they refresh their libraries.

I'd appreciate a quick feedback if/when you get to tests this to make sure the issue is resolved

**Comment by druedan** [comment] 2020-07-17 16:41
Hey, sorry for the late reply - whatever fixes you did seem to have done the trick, I am no longer getting the error and am able to collect values from the sensor.

The value read from the Co2 sensor spikes way up intermittently (~400 to ~65,000) but I am unsure if this is at all related.

**Comment by winkj** [comment] 2020-07-17 16:53
Thanks for the feedback.

I didn't touch the SGP code at all in this change, so that change you're seeing should be independent... the value sounds very high (and suspiciously close to 2^16 (the max value of the 16-bit field), but it should not be related to this change

**Comment by druedan** [comment] 2020-07-17 18:05
I figured as much - it's a uniform value each time so that makes sense. I'll just filter it out of my data.

**Closed** 2020-08-07 18:03 UTC
Labels: feedback
